## Traitement de la base sirene

In [127]:
import os 
import pandas as pd
import numpy as np

In [2]:
#ne pas oublier PEP 8

In [187]:
# déclaration des constantes 
DATA_DIR = '../data/external/'
PROCESSED_DIR = '../data/processed/'

ENTITES_FILENAME = 'StockUniteLegale_utf8.zip'
ETAB_FILENAME = 'StockEtablissement_utf8.zip'
NAF_REF_FILENAME = 'naf86.xlsx'
PS_CITIES_FILENAME = 'PS_communes.csv'

ACTIVITY_CODE = '86.'

## Préparation des entités

In [4]:
pd.read_csv(os.path.join(DATA_DIR, ENTITES_FILENAME), #concaténation du répertoire et du nom de fichier
            compression='zip',
            nrows= 1000 #limite à 1000 lignes la lecture
           ).head()

,siren,statutdiffusionunitelegale,unitepurgeeunitelegale,datecreationunitelegale,sigleunitelegale,sexeunitelegale,prenom1unitelegale,prenom2unitelegale,prenom3unitelegale,prenom4unitelegale,...,denominationunitelegale,denominationusuelle1unitelegale,denominationusuelle2unitelegale,denominationusuelle3unitelegale,categoriejuridiqueunitelegale,activiteprincipaleunitelegale,nomenclatureactiviteprincipaleunitelegale,nicsiegeunitelegale,economiesocialesolidaireunitelegale,caractereemployeurunitelegale
0,325175,O,NaN,2000-09-26,NaN,M,THIERRY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1000,32.12Z,NAFRev2,65,NaN,N
1,1807254,O,NaN,1972-05-01,NaN,M,JACQUES-LUCIEN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1000,85.59A,NAFRev2,22,NaN,N
2,5410220,O,True,1954-12-25,NaN,M,GEORGES,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1000,22.02,NAP,15,NaN,N
3,5410345,O,True,NaN,NaN,M,MICHEL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1000,79.06,NAP,10,NaN,N
4,5410394,O,True,1954-12-25,NaN,M,ROBERT,ALFRED,NaN,NaN,...,NaN,NaN,NaN,NaN,1000,64.42,NAP,18,NaN,N

In [5]:
pd.read_csv(os.path.join(DATA_DIR, ENTITES_FILENAME), #concaténation du répertoire et du nom de fichier
            compression='zip',
            nrows= 1000 #limite à 1000 lignes la lecture
           ).columns

Index(['siren', 'statutdiffusionunitelegale', 'unitepurgeeunitelegale',
       'datecreationunitelegale', 'sigleunitelegale', 'sexeunitelegale',
       'prenom1unitelegale', 'prenom2unitelegale', 'prenom3unitelegale',
       'prenom4unitelegale', 'prenomusuelunitelegale', 'pseudonymeunitelegale',
       'identifiantassociationunitelegale', 'trancheeffectifsunitelegale',
       'anneeeffectifsunitelegale', 'datederniertraitementunitelegale',
       'nombreperiodesunitelegale', 'categorieentreprise',
       'anneecategorieentreprise', 'datedebut', 'etatadministratifunitelegale',
       'nomunitelegale', 'nomusageunitelegale', 'denominationunitelegale',
       'denominationusuelle1unitelegale', 'denominationusuelle2unitelegale',
       'denominationusuelle3unitelegale', 'categoriejuridiqueunitelegale',
       'activiteprincipaleunitelegale',
       'nomenclatureactiviteprincipaleunitelegale', 'nicsiegeunitelegale',
       'economiesocialesolidaireunitelegale', 'caractereemployeurunitelegale'],
      dtype='object')

In [6]:
entities_df = (pd.read_csv(os.path.join(DATA_DIR, ENTITES_FILENAME), #concaténation du répertoire et du nom de fichier
                usecols= ['activiteprincipaleunitelegale', 'datecreationunitelegale', 'denominationunitelegale', 'nomunitelegale' ],
                compression='zip',
                nrows= 100000 #limite à 1000 lignes la lecture
                )
    ).dropna(subset=['activiteprincipaleunitelegale'])

(entities_df[entities_df.activiteprincipaleunitelegale.str.startswith(ACTIVITY_CODE)] #86.
['activiteprincipaleunitelegale']
.value_counts()
)

86.06     95
86.10     19
86.04     18
86.10Z     8
86.90B     6
86.11      4
86.05      4
86.02      2
86.12      2
86.08      2
86.09      1
86.23Z     1
86.90A     1
86.90E     1
86.90F     1
86.07      1
86.21Z     1
Name: activiteprincipaleunitelegale, dtype: int64

In [7]:
entities_df.shape

(99797, 4)

In [8]:
entities_df.denominationunitelegale.isnull().sum()

20222

In [9]:
entities_df.nomunitelegale.isnull().sum()

79575

In [10]:
entities_df.denominationunitelegale.isnull().sum() + entities_df.nomunitelegale.isnull().sum() == entities_df.shape[0]

True

In [11]:
entities_df = (pd.read_csv(os.path.join(DATA_DIR, ENTITES_FILENAME), #concaténation du répertoire et du nom de fichier
                usecols= ['activiteprincipaleunitelegale', 'datecreationunitelegale', 'denominationunitelegale', 'siren', 'nomunitelegale' ],
                compression='zip',
                #nrows= 100000 #limite à 1000 lignes la lecture
                )
    ).dropna(subset=['activiteprincipaleunitelegale'])

(entities_df[entities_df.activiteprincipaleunitelegale.str.startswith(ACTIVITY_CODE)] #86.
['activiteprincipaleunitelegale']
.value_counts()
)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

86.90D    171348
86.90E    144949
86.21Z    120266
86.90F    102522
86.22C     61179
86.23Z     57206
86.06      13225
86.90A      8767
86.07       8081
86.22A      7185
86.22B      7036
86.90B      5621
86.12       4329
86.10       3914
86.10Z      3793
86.08       2766
86.02       1748
86.04       1472
86.09        981
86.05        977
86.01        703
86.03        220
86.11        189
86.90C       149
Name: activiteprincipaleunitelegale, dtype: int64

In [34]:
entities_df = (pd.read_csv(os.path.join(DATA_DIR, ENTITES_FILENAME), #concaténation du répertoire et du nom de fichier
                usecols= ['activiteprincipaleunitelegale', 'datecreationunitelegale', 'siren', 'denominationunitelegale', 'nomunitelegale', 'etatadministratifunitelegale' ],
                compression='zip',
                #nrows= 100000 #limite à 1000 lignes la lecture
                )
    ).dropna(subset=['activiteprincipaleunitelegale']).query('etatadministratifunitelegale=="A"')



#entities_df = entities_df[entities_df.activiteprincipaleunitelegale.str.startswith(ACTIVITY_CODE)] #86.

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [36]:
entities_df.head()

,siren,datecreationunitelegale,etatadministratifunitelegale,nomunitelegale,denominationunitelegale,activiteprincipaleunitelegale
0,325175,2000-09-26,A,JANOYER,NaN,32.12Z
31,5411582,1954-01-01,A,GERVOISE,NaN,68.20B
38,5420021,1954-01-01,A,NaN,ETABLISSEMENTS LUCIEN BIQUEZ,46.69B
45,5420120,1954-01-01,A,NaN,SOCIETE DES SUCRERIES DU MARQUENTERRE,70.10Z
51,5420260,1954-12-25,A,NaN,SOCIETE ANONYME MILBLED,20.01

In [37]:
entities_df.shape

(11696143, 6)

## Préparation des établissements

In [15]:
pd.read_csv(os.path.join(DATA_DIR, ETAB_FILENAME), #concaténation du répertoire et du nom de fichier
            compression='zip',
            nrows= 1000 #limite à 1000 lignes la lecture
           ).head()

,siren,nic,siret,statutdiffusionetablissement,datecreationetablissement,trancheeffectifsetablissement,anneeeffectifsetablissement,activiteprincipaleregistremetiersetablissement,datederniertraitementetablissement,etablissementsiege,...,libellepaysetranger2etablissement,datedebut,etatadministratifetablissement,enseigne1etablissement,enseigne2etablissement,enseigne3etablissement,denominationusuelleetablissement,activiteprincipaleetablissement,nomenclatureactiviteprincipaleetablissement,caractereemployeuretablissement
0,325175,16,32517500016,O,2000-09-26,NaN,NaN,3212ZZ,2015-03-18T00:58:59,False,...,NaN,2009-05-27,F,NaN,NaN,NaN,NaN,32.12Z,NAFRev2,N
1,325175,24,32517500024,O,2008-05-20,NaN,NaN,NaN,2011-12-12T09:40:04,False,...,NaN,2011-10-21,F,TAHITI PERLES CREATIONS,NaN,NaN,NaN,47.89Z,NAFRev2,N
2,325175,32,32517500032,O,2009-05-27,NaN,NaN,NaN,2014-07-08T00:10:21,False,...,NaN,2011-10-21,F,TAHITI PERLES CREATIONS,NaN,NaN,NaN,32.12Z,NAFRev2,N
3,325175,40,32517500040,O,2011-10-21,NaN,NaN,3212ZZ,2015-03-18T00:58:59,False,...,NaN,2014-01-07,F,TAHITI PERLES CREATION,NaN,NaN,NaN,32.12Z,NAFRev2,N
4,325175,57,32517500057,O,2014-01-07,NaN,NaN,NaN,2018-07-10T14:17:15,False,...,NaN,2018-02-07,F,TAHITI PERLES CREATION,NaN,NaN,NaN,32.12Z,NAFRev2,N

In [16]:
pd.read_csv(os.path.join(DATA_DIR, ETAB_FILENAME), #concaténation du répertoire et du nom de fichier
            compression='zip',
            nrows= 1000 #limite à 1000 lignes la lecture
           ).columns.sort_values()

Index(['activiteprincipaleetablissement',
       'activiteprincipaleregistremetiersetablissement',
       'anneeeffectifsetablissement', 'caractereemployeuretablissement',
       'codecedex2etablissement', 'codecedexetablissement',
       'codecommune2etablissement', 'codecommuneetablissement',
       'codepaysetranger2etablissement', 'codepaysetrangeretablissement',
       'codepostal2etablissement', 'codepostaletablissement',
       'complementadresse2etablissement', 'complementadresseetablissement',
       'datecreationetablissement', 'datedebut',
       'datederniertraitementetablissement',
       'denominationusuelleetablissement',
       'distributionspeciale2etablissement',
       'distributionspecialeetablissement', 'enseigne1etablissement',
       'enseigne2etablissement', 'enseigne3etablissement',
       'etablissementsiege', 'etatadministratifetablissement',
       'indicerepetition2etablissement', 'indicerepetitionetablissement',
       'libellecedex2etablissement', 'libellecedexetablissement',
       'libellecommune2etablissement', 'libellecommuneetablissement',
       'libellecommuneetranger2etablissement',
       'libellecommuneetrangeretablissement',
       'libellepaysetranger2etablissement', 'libellepaysetrangeretablissement',
       'libellevoie2etablissement', 'libellevoieetablissement', 'nic',
       'nombreperiodesetablissement',
       'nomenclatureactiviteprincipaleetablissement',
       'numerovoie2etablissement', 'numerovoieetablissement', 'siren', 'siret',
       'statutdiffusionetablissement', 'trancheeffectifsetablissement',
       'typevoie2etablissement', 'typevoieetablissement'],
      dtype='object')

In [35]:
%%time
etab_df = (pd.read_csv(os.path.join(DATA_DIR, ETAB_FILENAME), #concaténation du répertoire et du nom de fichier
                usecols= ['activiteprincipaleetablissement', 'datecreationetablissement', 'denominationusuelleetablissement', 'etatadministratifetablissement', 
                          'codecommuneetablissement', 'codepostaletablissement', 'libellecommuneetablissement', 'siren'],
                compression='zip',
                #nrows= 100000 #limite à 1000 lignes la lecture
                )
    ).dropna(subset=['activiteprincipaleetablissement']).query('etatadministratifetablissement =="A"')

#filtrage des professionnels de santé
#etab_df = etab_df[etab_df.activiteprincipaleetablissement.str.startswith(ACTIVITY_CODE)] #86.

<string>:2: DtypeWarning: Columns (20,44) have mixed types. Specify dtype option on import or set low_memory=False.

Wall time: 1min 26s

In [38]:
etab_df.shape

(11233968, 8)

In [39]:
etab_df.head(40)

,siren,datecreationetablissement,codepostaletablissement,libellecommuneetablissement,codecommuneetablissement,etatadministratifetablissement,denominationusuelleetablissement,activiteprincipaleetablissement
5,325175,2018-02-07,13004.0,MARSEILLE 4,13204,A,NaN,32.12Z
48,5420021,2009-12-23,80100.0,ABBEVILLE,80001,A,NaN,46.69B
56,5420120,1989-01-27,80120.0,RUE,80688,A,NaN,10.81Z
57,5420120,1900-01-01,62180.0,RANG DU FLIERS,62688,A,NaN,52.10B
58,5420120,1900-01-01,62140.0,MARCONNELLE,62550,A,NaN,70.10Z
59,5420120,1900-01-01,62180.0,CONCHIL LE TEMPLE,62233,A,NaN,46.75Z
71,5440110,1995-10-01,4000.0,DIGNE-LES-BAINS,04070,A,NaN,68.20B
79,5440565,1954-01-01,4200.0,SISTERON,04209,A,NaN,68.20B
119,5450093,2001-02-20,4800.0,GREOUX LES BAINS,04094,A,PASSIONNEMENT GLAMOUR,47.78C
120,5450093,2011-04-12,4800.0,GREOUX LES BAINS,04094,A,PASSIONNEMENT GLAMOUR,47.71Z
124,5450119,1994-05-01,4000.0,DIGNE-LES-BAINS,04070,A,NaN,70.10Z
125,5450119,1994-05-01,4000.0,DIGNE-LES-BAINS,04070,A,NaN,56.30Z
153,5471800,1900-01-01,44350.0,GUERANDE,44069,A,NaN,68.20B
167,5472980,1954-01-01,44360.0,CORDEMAIS,44045,A,NaN,68.20B
171,5473202,1992-05-01,44220.0,COUERON,44047,A,NaN,68.20B
191,5474960,1954-01-01,44600.0,SAINT NAZAIRE,44184,A,NaN,68.20B
199,5480546,1958-01-01,44350.0,GUERANDE,44069,A,NaN,17.12Z
244,5520028,1955-01-01,80570.0,DARGNIES,80235,A,NaN,68.20B
246,5520077,1955-01-01,80210.0,FEUQUIERES EN VIMEU,80308,A,NaN,25.72Z
255,5520176,1955-01-01,80210.0,FEUQUIERES EN VIMEU,80308,A,NaN,17.21A
256,5520176,1999-08-30,80210.0,CHEPY,80190,A,NaN,17.21A
259,5520242,1900-01-01,80510.0,LONGPRE LES CORPS SAINTS,80488,A,NaN,20.30Z
267,5520325,1955-01-01,80570.0,DARGNIES,80235,A,NaN,46.74B
268,5520325,2018-12-20,75018.0,PARIS 18,75118,A,NaN,70.10Z
281,5540273,1900-01-01,4330.0,BARREME,04022,A,NaN,68.20B
296,5540661,1900-01-01,4000.0,DIGNE-LES-BAINS,04070,A,NaN,68.20B
312,5541206,1998-04-02,4320.0,ENTREVAUX,04076,A,NaN,68.20B
321,5541438,1990-09-01,4000.0,DIGNE-LES-BAINS,04070,A,NaN,68.20B
325,5541552,1974-01-01,4370.0,BEAUVEZER,04025,A,NaN,55.10Z
327,5541552,2007-09-30,4260.0,ALLOS,04006,A,NaN,56.10C
338,5541867,1984-07-10,83460.0,LES ARCS,83004,A,NaN,68.20B
487,5577325,1994-01-03,44350.0,GUERANDE,44069,A,NaN,68.20B
491,5580113,2018-12-20,44570.0,TRIGNAC,44210,A,NaN,68.20A
511,5580436,2012-07-06,85640.0,MOUCHAMPS,85153,A,NaN,70.22Z
513,5580501,1986-12-25,44600.0,SAINT NAZAIRE,44184,A,NaN,52.10A
516,5580501,1996-05-01,75008.0,PARIS 8,75108,A,NaN,52.10A
542,5611074,1961-01-01,80100.0,ABBEVILLE,80001,A,NaN,01.42Z
567,5620034,1956-01-01,80100.0,ABBEVILLE,80001,A,NaN,46.73A
568,5620034,2010-09-01,76370.0,ROUXMESNIL BOUTEILLES,76545,A,NaN,46.73A
573,5620117,1900-01-01,80100.0,ABBEVILLE,80001,A,DUBOIS,46.69C

In [40]:
etab_df.dtypes

siren                                 int64
datecreationetablissement            object
codepostaletablissement             float64
libellecommuneetablissement          object
codecommuneetablissement             object
etatadministratifetablissement       object
denominationusuelleetablissement     object
activiteprincipaleetablissement      object
dtype: object

In [41]:
entities_df.dtypes

siren                             int64
datecreationunitelegale          object
etatadministratifunitelegale     object
nomunitelegale                   object
denominationunitelegale          object
activiteprincipaleunitelegale    object
dtype: object

In [22]:
etab_df.memory_usage(deep=True).sum() / (1024 *1024)  #en mégaoctet

4069.7011575698853

In [23]:
process_df = etab_df.merge(entities_df, on='siren', how='left')

In [24]:
process_df.shape

(11233968, 13)

In [25]:
process_df[process_df.activiteprincipaleunitelegale.isnull()].shape

(23, 13)

In [43]:
pita = etab_df.merge(entities_df, on='siren', how='outer', indicator=True)

In [46]:
pita2 = pita[pita.activiteprincipaleetablissement.str.startswith(ACTIVITY_CODE) | pita.activiteprincipaleunitelegale.str.startswith(ACTIVITY_CODE)] #86.

In [69]:
pita2.shape

(581698, 14)

In [163]:
pita2.activiteprincipaleetablissement.value_counts()

86.90E    129716
86.90D    129127
86.21Z     93533
86.90F     74362
86.22C     49173
86.23Z     45071
86.10Z      9406
68.20A      8604
86.90A      8043
86.22A      8004
86.22B      6649
86.90B      6582
68.20B      1688
87.10A      1351
70.10Z      1349
88.99B       896
66.19A       605
47.99A       546
86.90C       437
85.42Z       374
49.32Z       282
01.21Z       270
01.49Z       269
01.43Z       237
90.03A       218
87.20B       205
87.10C       204
02.10Z       192
55.20Z       186
35.11Z       180
           ...
43.22A         1
38.32Z         1
66.30Z         1
64.99Z         1
46.38B         1
93.13Z         1
10.72Z         1
08.93Z         1
16.23Z         1
45.20B         1
71.11Z         1
23.49Z         1
46.39B         1
90.04Z         1
49.39B         1
79.90Z         1
47.59A         1
46.22Z         1
32.12Z         1
47.11B         1
46.34Z         1
20.41Z         1
43.91A         1
14.13Z         1
61.90Z         1
43.99C         1
10.89Z         1
41.20B         1
41.10D         1
15.12Z         1
Name: activiteprincipaleetablissement, Length: 275, dtype: int64

In [70]:
pita2.loc[(pita2.activiteprincipaleetablissement.str.startswith(ACTIVITY_CODE) ) & (pita2.activiteprincipaleunitelegale.str.startswith(ACTIVITY_CODE))].shape

(552149, 14)

In [71]:
#il y a 29 549 qui n'ont pas les mêmes activités

In [162]:
pd.crosstab(pita2['activiteprincipaleetablissement'], pita2['activiteprincipaleunitelegale'])

activiteprincipaleunitelegale,01.11Z,01.13Z,01.14Z,01.19Z,01.21Z,01.22Z,01.23Z,01.24Z,01.25Z,01.26Z,...,94.92Z,94.99Z,95.11Z,95.29Z,96.01B,96.02A,96.02B,96.03Z,96.04Z,96.09Z
activiteprincipaleetablissement,,,,,,,,,,,,,,,,,,,,,
00.00Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.11Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.13Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.14Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.19Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.21Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.22Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.23Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.24Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.25Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.26Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.28Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.29Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.30Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.41Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.42Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.43Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.44Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.45Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.46Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.47Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.49Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.50Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.61Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01.62Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
02.10Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
02.20Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
02.30Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
02.40Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
03.21Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88.10C,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88.91A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88.91B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88.99A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88.99B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90.01Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90.02Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90.03A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90.03B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90.04Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
91.03Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93.11Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93.12Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93.13Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93.19Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93.29Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94.12Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94.91Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94.92Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94.99Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95.11Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95.24Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95.29Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.01A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.01B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.02A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.02B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.03Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.04Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.09Z,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
pita2.head(2000)

,siren,datecreationetablissement,codepostaletablissement,libellecommuneetablissement,codecommuneetablissement,etatadministratifetablissement,denominationusuelleetablissement,activiteprincipaleetablissement,datecreationunitelegale,etatadministratifunitelegale,nomunitelegale,denominationunitelegale,activiteprincipaleunitelegale,_merge
58,5720164,1983-09-28,80100.0,ABBEVILLE,80001,A,NaN,86.10Z,1957-01-01,A,NaN,SA SAINTE-ISABELLE,86.10Z,both
416,7050040,1970-01-01,4510.0,AIGLUN,04001,A,NaN,86.10Z,1970-01-01,A,NaN,CENTRE DES CARMES,86.10Z,both
5115,17150533,1971-01-01,21000.0,DIJON,21231,A,NaN,86.10Z,1971-01-01,A,NaN,CLINIQUE LES ROSIERS,86.10Z,both
12308,24080749,2002-12-19,97600.0,MAMOUDZOU,97611,A,NaN,86.90B,2002-12-19,A,NaN,MAYO BIO SELARL,86.90B,both
14190,35204429,2009-01-01,31200.0,TOULOUSE,31555,A,NaN,86.23Z,1983-10-21,A,NaN,SAURAT PHILIPPE ET ISABELLE,86.23Z,both
14879,36220150,1997-01-27,6600.0,ANTIBES,06004,A,POLE ANTIBES SAINT JEAN,86.10Z,1962-01-01,A,NaN,MONTSINERY,86.10Z,both
15197,37240348,1985-01-01,39100.0,DOLE,39198,A,NaN,86.90B,1972-01-01,A,MONNET,NaN,86.90B,both
15198,37240348,2002-12-20,73450.0,VALLOIRE,73306,A,NaN,68.20B,1972-01-01,A,MONNET,NaN,86.90B,both
15242,37739802,2004-10-01,64100.0,BAYONNE,64102,A,NaN,86.21Z,2004-10-10,A,BUCHET,NaN,86.21Z,both
15243,37739802,2004-10-10,64200.0,BIARRITZ,64122,A,NaN,68.20B,2004-10-10,A,BUCHET,NaN,86.21Z,both
76138,46620241,1966-01-01,20117.0,OCANA,2A181,A,NaN,86.10Z,1966-01-01,A,NaN,MAISON CONVALESCENCE VALICELLI,86.10Z,both
76190,46750147,1967-01-01,59500.0,DOUAI,59178,A,NaN,86.10Z,1967-01-01,A,NaN,CLINIQUE DU PONT SAINT VAAST,86.10Z,both
76191,46750147,2007-11-01,59187.0,DECHY,59170,A,NaN,86.10Z,1967-01-01,A,NaN,CLINIQUE DU PONT SAINT VAAST,86.10Z,both
78153,54390315,2004-01-19,97600.0,MAMOUDZOU,97611,A,NaN,86.21Z,2004-01-19,A,NaN,CABINET DES JARDINS SELARL,86.21Z,both
78813,54805577,1900-01-01,13011.0,MARSEILLE 11,13211,A,NaN,86.10Z,1955-01-01,A,NaN,SOCIETE ANONYME SAINT ROCH,86.10Z,both
79231,55806673,1955-01-01,13011.0,MARSEILLE 11,13211,A,NaN,86.10Z,1955-01-01,A,NaN,LA BASTIDE,86.10Z,both
79242,55807838,2001-10-01,13008.0,MARSEILLE 8,13208,A,NaN,86.10Z,1955-01-01,A,NaN,CLINIQUE JUGE,86.10Z,both
79587,56803117,1956-01-01,13400.0,AUBAGNE,13005,A,NaN,86.10Z,1956-01-01,A,NaN,HOPITAL PRIVE LA CASAMANCE,86.10Z,both
80423,57818460,1957-01-01,13006.0,MARSEILLE 6,13206,A,NaN,86.10Z,1957-01-01,A,NaN,CLINIQUE BOUCHARD,86.10Z,both
80424,57818460,2003-07-31,13008.0,MARSEILLE 8,13208,A,NaN,86.10Z,1957-01-01,A,NaN,CLINIQUE BOUCHARD,86.10Z,both
80533,58504390,2016-06-03,38180.0,SEYSSINS,38486,A,NaN,86.10Z,1958-01-01,A,NaN,CLINIQUE DU DAUPHINE,86.10Z,both
81516,61800090,1961-01-01,13009.0,MARSEILLE 9,13209,A,NaN,86.10Z,1961-01-01,A,NaN,CLINIQUE L EMERAUDE,86.10Z,both
81517,61800090,2016-06-22,92800.0,PUTEAUX,92062,A,NaN,70.10Z,1961-01-01,A,NaN,CLINIQUE L EMERAUDE,86.10Z,both
81518,61800090,2017-12-30,83440.0,CALLIAN,83029,A,NaN,68.20B,1961-01-01,A,NaN,CLINIQUE L EMERAUDE,86.10Z,both
81580,62200241,2000-07-10,49800.0,TRELAZE,49353,A,NaN,86.10Z,1974-01-01,A,NaN,CLINIQUE SAINT LEONARD,86.10Z,both
81581,62200241,2003-07-01,49800.0,TRELAZE,49353,A,NaN,86.10Z,1974-01-01,A,NaN,CLINIQUE SAINT LEONARD,86.10Z,both
81970,63803654,2012-03-21,13290.0,AIX EN PROVENCE,13001,A,NaN,86.10Z,1963-01-01,A,NaN,PROVENCALE D'INVESTISSEMENTS,86.10Z,both
81974,63804033,1963-01-01,13600.0,CEYRESTE,13023,A,NaN,86.10Z,1963-01-01,A,NaN,CENTRE MEDICAL DIETETIQUE LES PALMIERS,86.10Z,both
81979,63804447,1963-01-01,13004.0,MARSEILLE 4,13204,A,NaN,86.10Z,1963-01-01,A,NaN,CLINIQUE CHIRURGICALE SAINT-BERNARD,86.10Z,both
82005,64200728,1998-04-01,49300.0,CHOLET,49099,A,NaN,86.21Z,1964-01-01,A,NaN,AUDITION BRESSOLLETTE TRAINEAU,86.21Z,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274787,220700017,1904-04-04,7100.0,ANNONAY,07010,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARDECHE,84.11Z,both
274788,220700017,1904-04-04,7800.0,LA VOULTE SUR RHONE,07349,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARDECHE,84.11Z,both
274789,220700017,1904-04-04,7000.0,PRIVAS,07186,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARDECHE,84.11Z,both
274790,220700017,1904-04-04,7200.0,AUBENAS,07019,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARDECHE,84.11Z,both
274791,220700017,1989-01-01,7300.0,TOURNON SUR RHONE,07324,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARDECHE,84.11Z,both
274799,220700017,2011-01-01,7000.0,PRIVAS,07186,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARDECHE,84.11Z,both
274807,220800049,1990-11-28,8300.0,RETHEL,08362,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DES ARDENNES,84.11Z,both
274855,220900013,1985-01-07,9000.0,FOIX,09122,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274858,220900013,1904-04-04,9500.0,MIREPOIX,09194,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274859,220900013,1976-06-24,9300.0,LAVELANET,09160,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274865,220900013,2004-04-22,9100.0,PAMIERS,09225,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274867,220900013,2004-04-22,9400.0,TARASCON SUR ARIEGE,09306,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274895,220900013,2011-01-01,9130.0,LE FOSSAT,09124,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274896,220900013,2011-01-01,9300.0,LAVELANET,09160,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274897,220900013,2011-02-22,9200.0,SAINT GIRONS,09261,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274898,220900013,2011-02-23,9500.0,MIREPOIX,09194,A,NaN,86.21Z,1983-03-01,A,NaN,DEPARTEMENT DE L ARIEGE,84.11Z,both
274914,221000052,1987-10-17,10000.0,TROYES,10387,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274916,221000052,1985-05-01,10000.0,TROYES,10387,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274917,221000052,1993-04-01,10160.0,AIX-VILLEMAUR-PALIS,10003,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274919,221000052,1993-04-01,10200.0,BAR SUR AUBE,10033,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274920,221000052,1993-04-01,10110.0,BAR SUR SEINE,10034,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274921,221000052,1993-04-01,10100.0,ROMILLY SUR SEINE,10323,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274922,221000052,1993-04-01,10000.0,TROYES,10387,A,NaN,86.21Z,1978-01-01,A,NaN,DEPARTEMENT DE L AUBE,84.11Z,both
274942,221100019,1984-11-08,11100.0,NARBONNE,11262,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both
274943,221100019,1984-11-08,11300.0,LIMOUX,11206,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both
274944,221100019,1984-11-08,11200.0,LEZIGNAN CORBIERES,11203,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both
274945,221100019,1984-11-08,11500.0,QUILLAN,11304,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both
274948,221100019,1904-04-04,11000.0,CARCASSONNE,11069,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both
274949,221100019,1904-04-04,11400.0,CASTELNAUDARY,11076,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both
274950,221100019,1989-11-21,11000.0,CARCASSONNE,11069,A,NaN,86.21Z,1982-01-01,A,NaN,DEPARTEMENT DE L AUDE,84.11Z,both

In [105]:
pita3 = (pita2.assign(etab_ape_l1 = lambda df: df.activiteprincipaleetablissement.str.slice(0,2))
 .assign(el_ape_l1 = lambda df: df.activiteprincipaleunitelegale.str.slice(0,2))
 .assign(cross_l1 = lambda df: df.el_ape_l1 + df.etab_ape_l1)
)

In [100]:
pita3.head(100)

,siren,datecreationetablissement,codepostaletablissement,libellecommuneetablissement,codecommuneetablissement,etatadministratifetablissement,denominationusuelleetablissement,activiteprincipaleetablissement,datecreationunitelegale,etatadministratifunitelegale,nomunitelegale,denominationunitelegale,activiteprincipaleunitelegale,_merge,etab_ape_l1,el_ape_l1,cross_l1
58,5720164,1983-09-28,80100.0,ABBEVILLE,80001,A,NaN,86.10Z,1957-01-01,A,NaN,SA SAINTE-ISABELLE,86.10Z,both,86,86,8686
416,7050040,1970-01-01,4510.0,AIGLUN,04001,A,NaN,86.10Z,1970-01-01,A,NaN,CENTRE DES CARMES,86.10Z,both,86,86,8686
5115,17150533,1971-01-01,21000.0,DIJON,21231,A,NaN,86.10Z,1971-01-01,A,NaN,CLINIQUE LES ROSIERS,86.10Z,both,86,86,8686
12308,24080749,2002-12-19,97600.0,MAMOUDZOU,97611,A,NaN,86.90B,2002-12-19,A,NaN,MAYO BIO SELARL,86.90B,both,86,86,8686
14190,35204429,2009-01-01,31200.0,TOULOUSE,31555,A,NaN,86.23Z,1983-10-21,A,NaN,SAURAT PHILIPPE ET ISABELLE,86.23Z,both,86,86,8686
14879,36220150,1997-01-27,6600.0,ANTIBES,06004,A,POLE ANTIBES SAINT JEAN,86.10Z,1962-01-01,A,NaN,MONTSINERY,86.10Z,both,86,86,8686
15197,37240348,1985-01-01,39100.0,DOLE,39198,A,NaN,86.90B,1972-01-01,A,MONNET,NaN,86.90B,both,86,86,8686
15198,37240348,2002-12-20,73450.0,VALLOIRE,73306,A,NaN,68.20B,1972-01-01,A,MONNET,NaN,86.90B,both,68,86,8668
15242,37739802,2004-10-01,64100.0,BAYONNE,64102,A,NaN,86.21Z,2004-10-10,A,BUCHET,NaN,86.21Z,both,86,86,8686
15243,37739802,2004-10-10,64200.0,BIARRITZ,64122,A,NaN,68.20B,2004-10-10,A,BUCHET,NaN,86.21Z,both,68,86,8668
76138,46620241,1966-01-01,20117.0,OCANA,2A181,A,NaN,86.10Z,1966-01-01,A,NaN,MAISON CONVALESCENCE VALICELLI,86.10Z,both,86,86,8686
76190,46750147,1967-01-01,59500.0,DOUAI,59178,A,NaN,86.10Z,1967-01-01,A,NaN,CLINIQUE DU PONT SAINT VAAST,86.10Z,both,86,86,8686
76191,46750147,2007-11-01,59187.0,DECHY,59170,A,NaN,86.10Z,1967-01-01,A,NaN,CLINIQUE DU PONT SAINT VAAST,86.10Z,both,86,86,8686
78153,54390315,2004-01-19,97600.0,MAMOUDZOU,97611,A,NaN,86.21Z,2004-01-19,A,NaN,CABINET DES JARDINS SELARL,86.21Z,both,86,86,8686
78813,54805577,1900-01-01,13011.0,MARSEILLE 11,13211,A,NaN,86.10Z,1955-01-01,A,NaN,SOCIETE ANONYME SAINT ROCH,86.10Z,both,86,86,8686
79231,55806673,1955-01-01,13011.0,MARSEILLE 11,13211,A,NaN,86.10Z,1955-01-01,A,NaN,LA BASTIDE,86.10Z,both,86,86,8686
79242,55807838,2001-10-01,13008.0,MARSEILLE 8,13208,A,NaN,86.10Z,1955-01-01,A,NaN,CLINIQUE JUGE,86.10Z,both,86,86,8686
79587,56803117,1956-01-01,13400.0,AUBAGNE,13005,A,NaN,86.10Z,1956-01-01,A,NaN,HOPITAL PRIVE LA CASAMANCE,86.10Z,both,86,86,8686
80423,57818460,1957-01-01,13006.0,MARSEILLE 6,13206,A,NaN,86.10Z,1957-01-01,A,NaN,CLINIQUE BOUCHARD,86.10Z,both,86,86,8686
80424,57818460,2003-07-31,13008.0,MARSEILLE 8,13208,A,NaN,86.10Z,1957-01-01,A,NaN,CLINIQUE BOUCHARD,86.10Z,both,86,86,8686
80533,58504390,2016-06-03,38180.0,SEYSSINS,38486,A,NaN,86.10Z,1958-01-01,A,NaN,CLINIQUE DU DAUPHINE,86.10Z,both,86,86,8686
81516,61800090,1961-01-01,13009.0,MARSEILLE 9,13209,A,NaN,86.10Z,1961-01-01,A,NaN,CLINIQUE L EMERAUDE,86.10Z,both,86,86,8686
81517,61800090,2016-06-22,92800.0,PUTEAUX,92062,A,NaN,70.10Z,1961-01-01,A,NaN,CLINIQUE L EMERAUDE,86.10Z,both,70,86,8670
81518,61800090,2017-12-30,83440.0,CALLIAN,83029,A,NaN,68.20B,1961-01-01,A,NaN,CLINIQUE L EMERAUDE,86.10Z,both,68,86,8668
81580,62200241,2000-07-10,49800.0,TRELAZE,49353,A,NaN,86.10Z,1974-01-01,A,NaN,CLINIQUE SAINT LEONARD,86.10Z,both,86,86,8686
81581,62200241,2003-07-01,49800.0,TRELAZE,49353,A,NaN,86.10Z,1974-01-01,A,NaN,CLINIQUE SAINT LEONARD,86.10Z,both,86,86,8686
81970,63803654,2012-03-21,13290.0,AIX EN PROVENCE,13001,A,NaN,86.10Z,1963-01-01,A,NaN,PROVENCALE D'INVESTISSEMENTS,86.10Z,both,86,86,8686
81974,63804033,1963-01-01,13600.0,CEYRESTE,13023,A,NaN,86.10Z,1963-01-01,A,NaN,CENTRE MEDICAL DIETETIQUE LES PALMIERS,86.10Z,both,86,86,8686
81979,63804447,1963-01-01,13004.0,MARSEILLE 4,13204,A,NaN,86.10Z,1963-01-01,A,NaN,CLINIQUE CHIRURGICALE SAINT-BERNARD,86.10Z,both,86,86,8686
82005,64200728,1998-04-01,49300.0,CHOLET,49099,A,NaN,86.21Z,1964-01-01,A,NaN,AUDITION BRESSOLLETTE TRAINEAU,86.21Z,both,86,86,8686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91133,130003569,2011-01-01,17640.0,VAUX SUR MER,17461,A,NaN,86.90B,2006-12-25,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE DE SAINTON...,86.90B,both,86,86,8686
91134,130003569,2017-12-28,17500.0,JONZAC,17197,A,NaN,86.90B,2006-12-25,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE DE SAINTON...,86.90B,both,86,86,8686
91136,130003585,2006-03-22,76000.0,ROUEN,76540,A,NaN,86.10Z,2006-03-22,A,NaN,GCS MAINTENANCE DEVELOPPEMENT SYSTEME INFORMAT...,86.10Z,both,86,86,8686
91153,130003882,2012-05-14,77100.0,MEAUX,77284,A,NaN,86.10Z,2005-05-04,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE DE MOYENS ...,86.10Z,both,86,86,8686
91167,130004096,2007-11-07,94120.0,FONTENAY SOUS BOIS,94033,A,NaN,86.90D,2007-07-26,A,NaN,GROUPEMENT DE COOPERATION SOCIALE ET MEDICO SO...,87.30A,both,86,87,8786
91168,130004096,2010-04-14,94120.0,FONTENAY SOUS BOIS,94033,A,NaN,86.10Z,2007-07-26,A,NaN,GROUPEMENT DE COOPERATION SOCIALE ET MEDICO SO...,87.30A,both,86,87,8786
91191,130004484,2007-03-02,12300.0,DECAZEVILLE,12089,A,NaN,86.22A,2007-03-02,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE D IMAGERIE...,86.22A,both,86,86,8686
91317,130005192,2008-07-08,16470.0,SAINT MICHEL,16341,A,NaN,86.22A,2008-07-08,A,NaN,GROUPEMENT CHARENTAIS DE COOPERATION EN RADIOT...,86.22A,both,86,86,8686
91320,130005226,2008-07-01,85300.0,CHALLANS,85047,A,NaN,86.10Z,2008-07-01,A,NaN,GROUPEMENT COOPERATION SANITAIRE MARAIS BRETON...,86.10Z,both,86,86,8686
91381,130005457,2009-01-01,67000.0,STRASBOURG,67482,A,NaN,86.21Z,2008-08-18,A,NaN,UNIVERSITE DE STRASBOURG,85.42Z,both,86,85,8586
92596,130005796,2008-05-19,17640.0,VAUX SUR MER,17461,A,NaN,86.10Z,2008-05-19,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE URGENCES D...,86.10Z,both,86,86,8686
92597,130005796,2009-07-01,17110.0,SAINT GEORGES DE DIDONNE,17333,A,NaN,86.10Z,2008-05-19,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE URGENCES D...,86.10Z,both,86,86,8686
92598,130005796,2008-07-01,17200.0,ROYAN,17306,A,NaN,86.10Z,2008-05-19,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE URGENCES D...,86.10Z,both,86,86,8686
92599,130005796,2008-05-19,17640.0,VAUX SUR MER,17461,A,NaN,86.10Z,2008-05-19,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE URGENCES D...,86.10Z,both,86,86,8686
93350,130007313,2015-11-05,65000.0,TARBES,65440,A,NaN,86.22C,2009-07-07,A,NaN,GROUPEMENT D'INTERET PUBLIC POUR LE DEPISTAGE ...,86.22C,both,86,86,8686
93353,130007339,2014-10-01,16470.0,SAINT MICHEL,16341,A,NaN,86.90D,2009-11-01,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE DES ETABLI...,84.12Z,both,86,84,8486
93354,130007339,2012-01-01,16300.0,BARBEZIEUX SAINT HILAIRE,16028,A,NaN,86.90B,2009-11-01,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE DES ETABLI...,84.12Z,both,86,84,8486
93395,130007743,2007-12-07,51300.0,VITRY LE FRANCOIS,51649,A,NaN,86.10Z,2007-12-07,A,NaN,GCS DER ET PERTHOIS,86.10Z,both,86,86,8686
93396,130007743,2009-12-14,51300.0,VITRY LE FRANCOIS,51649,A,NaN,86.10Z,2007-12-07,A,NaN,GCS DER ET PERTHOIS,86.10Z,both,86,86,8686
93589,130008212,2009-01-05,35300.0,FOUGERES,35115,A,NaN,86.10Z,2009-01-05,A,NaN,GROUPEMENT SANITAIRE DU PAYS DE FOUGERES,86.10Z,both,86,86,8686
93590,130008220,2009-06-22,59000.0,LILLE,59350,A,NaN,86.10Z,2009-06-22,A,NaN,STERINORD,86.10Z,both,86,86,8686
94506,130009855,2009-01-27,39100.0,DOLE,39198,A,NaN,86.10Z,2009-01-27,A,NaN,GCS RESEAU REGIONAL DES URGENCES DE FRANCHE-COMTE,86.10Z,both,86,86,8686
95453,130010754,2010-02-01,33520.0,BRUGES,33075,A,NaN,86.90D,2009-12-16,A,NaN,GROUPEMENT COOPERATION SOCIALE ET MEDICO SOCIA...,84.12Z,both,86,84,8486
98563,130013857,2010-03-12,97220.0,TRINITE,97230,A,NaN,86.22A,2010-03-12,A,NaN,GROUPEMENT COOPERATION SANITAIRE IRM TRINITE L...,86.22A,both,86,86,8686
99128,130014921,2009-01-07,51000.0,CHALONS EN CHAMPAGNE,51108,A,NaN,86.10Z,2009-01-07,A,NaN,GROUPEMENT DE COOPERATION SANITAIRE POLE DE SA...,86.10Z,both,86,86,8686
99288,130014954,2011-05-02,69400.0,GLEIZE,69092,A,NaN,86.10Z,2011-05-02,A,NaN,GCS CENTRE D'ANGIOPLASTIE DU BEAUJOLAIS,86.10Z,both,86,86,8686
99297,130015076,2009-03-17,33210.0,LANGON,33227,A,NaN,86.22A,2009-03-17,A,NaN,POLE D'IMAGERIE MEDICALE DU SUD GIRONDE,86.22A,both,86,86,8686
99370,130015308,2009-09-23,52000.0,CHAUMONT,52121,A,NaN,86.10Z,2009-09-23,A,NaN,GCS POLE CANCEROLOGIE SUD HAUT MARNAIS,86.10Z,both,86,86,8686
99371,130015308,2009-09-23,52000.0,CHAUMONT,52121,A,NaN,86.10Z,2009-09-23,A,NaN,GCS POLE CANCEROLOGIE SUD HAUT MARNAIS,86.10Z,both,86,86,8686
99372,130015308,2009-09-23,52000.0,CHAUMONT,52121,A,NaN,86.10Z,2009-09-23,A,NaN,GCS POLE CANCEROLOGIE SUD HAUT MARNAIS,86.10Z,both,86,86,8686

In [98]:
pd.crosstab(pita3.el_ape_l1, pita3.etab_ape_l1)

etab_ape_l1,00,01,02,03,08,10,11,13,14,15,...,85,86,87,88,90,91,93,94,95,96
el_ape_l1,,,,,,,,,,,,,,,,,,,,,
01,0,0,0,0,0,0,0,0,0,0,...,0,332,0,0,0,0,0,0,0,0
02,0,0,0,0,0,0,0,0,0,0,...,0,35,0,0,0,0,0,0,0,0
03,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
05,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,...,0,13,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,...,0,23,0,0,0,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,...,0,11,0,0,0,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,...,0,39,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,257,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,...,0,85,0,0,0,0,0,0,0,0
50,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
53,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
55,0,0,0,0,0,0,0,0,0,0,...,0,42,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,...,0,35,0,0,0,0,0,0,0,0
58,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
62,0,0,0,0,0,0,0,0,0,0,...,0,7,0,0,0,0,0,0,0,0
63,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,0,0,0,0,0,0
64,0,0,0,0,0,0,0,0,0,0,...,0,13,0,0,0,0,0,0,0,0
65,0,0,0,0,0,0,0,0,0,0,...,0,772,0,0,0,0,0,0,0,0
66,0,0,0,0,0,0,0,0,0,0,...,0,44,0,0,0,0,0,0,0,0
68,0,0,0,0,0,0,0,0,0,0,...,0,313,0,0,0,0,0,0,0,0
69,0,0,0,0,0,0,0,0,0,0,...,0,8,0,0,0,0,0,0,0,0
70,0,0,0,0,0,0,0,0,0,0,...,0,149,0,0,0,0,0,0,0,0
71,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
72,0,0,0,0,0,0,0,0,0,0,...,0,15,0,0,0,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
74,0,0,0,0,0,0,0,0,0,0,...,0,50,0,0,0,0,0,0,0,0
75,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
77,0,0,0,0,0,0,0,0,0,0,...,0,9,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
81,0,0,0,0,0,0,0,0,0,0,...,0,9,0,0,0,0,0,0,0,0
82,0,0,0,0,0,0,0,0,0,0,...,0,65,0,0,0,0,0,0,0,0
84,0,0,0,0,0,0,0,0,0,0,...,0,3477,0,0,0,0,0,0,0,0
85,0,0,0,0,0,0,0,0,0,0,...,0,214,0,0,0,0,0,0,0,0
86,2,1336,242,5,1,8,1,3,5,2,...,733,552149,2259,1448,357,2,44,66,7,408
87,0,0,0,0,0,0,0,0,0,0,...,0,352,0,0,0,0,0,0,0,0
88,0,0,0,0,0,0,0,0,0,0,...,0,944,0,0,0,0,0,0,0,0
90,0,0,0,0,0,0,0,0,0,0,...,0,116,0,0,0,0,0,0,0,0
93,0,0,0,0,0,0,0,0,0,0,...,0,30,0,0,0,0,0,0,0,0
94,0,0,0,0,0,0,0,0,0,0,...,0,205,0,0,0,0,0,0,0,0
95,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,207,0,0,0,0,0,0,0,0

In [101]:
pita3.cross_l1.value_counts()

8686    552149
8668     10368
8486      3477
8687      2259
8688      1448
8670      1405
8601      1336
8886       944
6586       772
8647       761
8685       733
8666       617
8696       408
8690       357
8786       352
8655       342
0186       332
6886       313
8649       302
4786       257
8602       242
8586       214
9686       207
9486       205
8635       180
7086       149
9086       116
8674        89
8682        87
4986        85
         ...
6386         3
3386         2
8691         2
8615         2
8638         2
1386         2
8600         2
7186         2
7986         2
4186         2
8665         2
2186         1
8625         1
8661         1
2886         1
7886         1
5086         1
0586         1
8618         1
8629         1
1186         1
8608         1
3186         1
8679         1
1586         1
8627         1
1486         1
8680         1
8611         1
8622         1
Name: cross_l1, Length: 121, dtype: int64

In [125]:
pita3.cross_l1.value_counts(normalize=True).head()

8686    0.949202
8668    0.017824
8486    0.005977
8687    0.003883
8688    0.002489
Name: cross_l1, dtype: float64

In [102]:
%load_ext dpaste_magic

In [ ]:
# %load https://dpaste.de/SWEe/raw
#ps_df = (merged_df.loc[merged_df.activiteprincipaleunitelegale.str.startswith("86.") |
#                      merged_df.activiteprincipaleetablissement.str.startswith("86.")]
#         .assign(etab_ape_l1 = lambda df: df.activiteprincipaleetablissement.str.slice(0, 2))
#         .assign(el_ape_l1 = lambda x: x.activiteprincipaleunitelegale.str.slice(0, 2))
#         .assign(cross_l1 = lambda df: df.el_ape_l1 + '_' + df.etab_ape_l1)
#        )
#merged_df = (etab_df.merge(entities_df, on='siren', how='outer', indicator=True)

In [ ]:
#%getdpaste SWEe
#%%dpaste

In [106]:
pd.crosstab(pita3.query('cross_l1 == "8686"').activiteprincipaleetablissement,
            pita3.query('cross_l1 == "8686"').activiteprincipaleunitelegale)

activiteprincipaleunitelegale,86.10Z,86.21Z,86.22A,86.22B,86.22C,86.23Z,86.90A,86.90B,86.90C,86.90D,86.90E,86.90F
activiteprincipaleetablissement,,,,,,,,,,,,
86.10Z,8736,12,8,2,1,0,0,0,0,6,1,0
86.21Z,312,88879,202,68,423,15,0,6,6,19,9,10
86.22A,11,207,7618,0,100,0,0,0,0,1,0,0
86.22B,4,97,0,6410,106,6,0,0,0,0,0,1
86.22C,17,634,216,186,47899,12,0,10,0,1,2,8
86.23Z,9,4,0,16,7,44336,0,0,0,1,1,0
86.90A,35,0,0,0,0,0,7866,0,1,1,0,0
86.90B,15,10,3,0,24,0,0,6450,1,3,0,0
86.90C,14,0,0,0,0,0,0,0,422,0,0,0
86.90D,322,15,2,1,5,4,0,3,0,127363,85,61
86.90E,4,12,0,0,2,1,0,1,0,158,128853,349
86.90F,9,22,1,0,9,2,3,8,0,251,169,72954

In [107]:
#86.1: hopitaux
#86.2: medecin + dentistes
#86.9: autres
#86.22C à 86.21Z ==> cafouillages

In [ ]:
# %load https://dpaste.de/fYex/raw
https://www.insee.fr/fr/information/2120875
#A partir de https://www.insee.fr/fr/information/2120875, copier ce qui nous intéresse

### Préparation de la table des codes NAF

In [123]:
#copie colle la table + enregistre dans un excel
naf_df = pd.read_clipboard() 
naf_df.to_excel(os.path.join(DATA_DIR, NAF_REF_FILENAME), index = False)

In [124]:
naf_df.head()

      NAF                                           Libellé          Catégorie
0  86.10Z                           Activités hospitalières           hopital
1  86.21Z                Activité des médecins généralistes        generaliste
2  86.22A  Activités de radiodiagnostic et de radiothérapie       radiologiste
3  86.22B                           Activités chirurgicales         chirurgien
4  86.22C        Autres activités des médecins spécialistes  autre_specialiste

In [126]:
pita3.head()

,siren,datecreationetablissement,codepostaletablissement,libellecommuneetablissement,codecommuneetablissement,etatadministratifetablissement,denominationusuelleetablissement,activiteprincipaleetablissement,datecreationunitelegale,etatadministratifunitelegale,nomunitelegale,denominationunitelegale,activiteprincipaleunitelegale,_merge,etab_ape_l1,el_ape_l1,cross_l1
58,5720164,1983-09-28,80100.0,ABBEVILLE,80001,A,NaN,86.10Z,1957-01-01,A,NaN,SA SAINTE-ISABELLE,86.10Z,both,86,86,8686
416,7050040,1970-01-01,4510.0,AIGLUN,04001,A,NaN,86.10Z,1970-01-01,A,NaN,CENTRE DES CARMES,86.10Z,both,86,86,8686
5115,17150533,1971-01-01,21000.0,DIJON,21231,A,NaN,86.10Z,1971-01-01,A,NaN,CLINIQUE LES ROSIERS,86.10Z,both,86,86,8686
12308,24080749,2002-12-19,97600.0,MAMOUDZOU,97611,A,NaN,86.90B,2002-12-19,A,NaN,MAYO BIO SELARL,86.90B,both,86,86,8686
14190,35204429,2009-01-01,31200.0,TOULOUSE,31555,A,NaN,86.23Z,1983-10-21,A,NaN,SAURAT PHILIPPE ET ISABELLE,86.23Z,both,86,86,8686

In [151]:
%%dpaste
pita3['NAF'] = np.where(pita3['etab_ape_l1'] == '86', 
                                pita3['activiteprincipaleetablissement'], 
                                pita3['activiteprincipaleunitelegale'])

https://dpaste.de/TUga

In [152]:
#pita3.head(100000)

In [164]:
pita4 = pita3.merge(naf_df, on='NAF', how='inner') #on merge avec la table référence

In [167]:
#pita4.head(100)

In [148]:
#Autre méthode 1
#ps_df.loc[ps_df.cross_l1 == '86_86', 'code_activite'] = ps_df.activiteprincipaleetablissement
#ps_df.loc[ps_df.el_ape_l1 != "86", 'code_activite'] = ps_df.activiteprincipaleetablissement
#ps_df.loc[~(ps_df.activiteprincipaleetablissement.str.startswith(ACTIVITY_CODE)), 'code_activite'] = ps_df.activiteprincipaleunitelegale

In [150]:
#pita4.drop(['unique_code'], axis=1)

In [157]:
#Autre méthode 2
pita3['code_activite'] = pita3.apply(lambda x: x.activiteprincipaleetablissement
                                    if x.etab_ape_l1 == "86"
                                    else x.activiteprincipaleunitelegale,
                                    axis=1
                                    ) # axis = 1 signifie colonne, sinn c'est 0

In [156]:
#Autre méthode 3, on crée une nouvelle colonne et on corrige après
pita3['code_activite']= pita3.activiteprincipaleetablissement
pita3['code_activite'] = pita3.where(pita3.etab_ape_l1 != 86,
                                    pita3.activiteprincipaleunitelegale,
                                     axis=1
                                    )

In [160]:
pita3.code_activite.value_counts()

86.90E    132626
86.90D    131850
86.21Z     97022
86.90F     75981
86.22C     51576
86.23Z     47039
86.10Z     14087
86.90A      8687
86.22A      8508
86.22B      7103
86.90B      6779
86.90C       440
Name: code_activite, dtype: int64

In [161]:
pita3.head()

,siren,datecreationetablissement,codepostaletablissement,libellecommuneetablissement,codecommuneetablissement,etatadministratifetablissement,denominationusuelleetablissement,activiteprincipaleetablissement,datecreationunitelegale,etatadministratifunitelegale,nomunitelegale,denominationunitelegale,activiteprincipaleunitelegale,_merge,etab_ape_l1,el_ape_l1,cross_l1,unique_code,NAF,code_activite
58,5720164,1983-09-28,80100.0,ABBEVILLE,80001,A,NaN,86.10Z,1957-01-01,A,NaN,SA SAINTE-ISABELLE,86.10Z,both,86,86,8686,86.10Z,86.10Z,86.10Z
416,7050040,1970-01-01,4510.0,AIGLUN,04001,A,NaN,86.10Z,1970-01-01,A,NaN,CENTRE DES CARMES,86.10Z,both,86,86,8686,86.10Z,86.10Z,86.10Z
5115,17150533,1971-01-01,21000.0,DIJON,21231,A,NaN,86.10Z,1971-01-01,A,NaN,CLINIQUE LES ROSIERS,86.10Z,both,86,86,8686,86.10Z,86.10Z,86.10Z
12308,24080749,2002-12-19,97600.0,MAMOUDZOU,97611,A,NaN,86.90B,2002-12-19,A,NaN,MAYO BIO SELARL,86.90B,both,86,86,8686,86.90B,86.90B,86.90B
14190,35204429,2009-01-01,31200.0,TOULOUSE,31555,A,NaN,86.23Z,1983-10-21,A,NaN,SAURAT PHILIPPE ET ISABELLE,86.23Z,both,86,86,8686,86.23Z,86.23Z,86.23Z

In [166]:
pita4.shape

(581698, 22)

# Ajout du type de PS & sauvegarde

In [ ]:
#Merge si les colonnes n'ont pas les mêmes noms
#ps_df.merge(naf_df, how='inner', left_on='code_activite', right_on='NAF')

In [189]:
#Transposition de la table et rassemblement des types de catégorie par communes
( pita3
 .merge(naf_df, on='NAF', how='inner')
 [['codecommuneetablissement', 'Catégorie']]
 .dropna(subset=['codecommuneetablissement'])
 .assign(count=1)
 .groupby(['codecommuneetablissement','Catégorie'])
 .sum()
 .reset_index()
 .pivot(index='codecommuneetablissement', columns='Catégorie', values='count')
 #.unstack(level=1)
 .fillna(0)
).to_csv(os.path.join(PROCESSED_DIR, PS_CITIES_FILENAME), sep=";")